@startuml
start
:El usuario entra a la aplicación;
if (¿El usuario se registra?) then (Sí)
  :Ingresar nombre, contraseña y correo;
else (No)
  :El usuario inicia sesión;
endif
:Ver menú;
:Entrar a reserva;
if (¿Confirmar reserva?) then (Sí)
  :Realizar pedido;
  :Pagar pedido;
  if (¿Generar reporte?) then (Sí)
    :Reporte generado;
  endif
  :Venta finalizada;
else (No)
  :Cancelar o editar reserva;
endif
stop
@enduml
